# Generated by Django 5.1.3 on 2024-12-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='название ингредиента'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('граммы', 'граммы'), ('килограммы', 'килограммы'), ('миллилитры', 'миллилитры'), ('литры', 'литры'), ('штуки', 'штуки')], max_length=50, null=True),
        ),
    ]
