# Generated by Django 5.1.3 on 2024-12-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resipe', '0002_alter_ingredient_name_alter_ingredient_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recipes', models.ManyToManyField(related_name='collections', to='resipe.recipe')),
            ],
        ),
    ]
