# Generated by Django 5.1.3 on 2024-12-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resipe', '0003_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
