# Generated by Django 5.1.3 on 2024-12-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0001_initial'),
        ('book_tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketmodel',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='книги', to='book_tags.books'),
        ),
    ]
