# Generated by Django 5.1.3 on 2024-12-18 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0002_alter_basketmodel_book'),
        ('book_tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketmodel',
            name='book',
            field=models.ForeignKey(choices=[('выполнена', 'выполнена'), ('неивыполнена', 'не выполнена')], null=True, on_delete=django.db.models.deletion.CASCADE, to='book_tags.books'),
        ),
    ]
